//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stats_V3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Formulari
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Formulari()
        {
            this.FormulariDetajets = new HashSet<FormulariDetajet>();
        }
    
        public int Id { get; set; }
        public int GjenerataId { get; set; }
        public int GjysmevjetoriId { get; set; }
        public Nullable<int> ShkollaId { get; set; }
        public Nullable<int> MungesaMeArsye { get; set; }
        public Nullable<int> MungesaPaArsye { get; set; }
    
        public virtual Gjenerata Gjenerata { get; set; }
        public virtual Gjysmevjetori Gjysmevjetori { get; set; }
        public virtual Shkolla Shkolla { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormulariDetajet> FormulariDetajets { get; set; }
    }
}
