//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stats_V3
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class Formulari
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Formulari()
        {
            this.FormulariDetajets = new HashSet<FormulariDetajet>();
        }
    
        public int Id { get; set; }
        [Display(Name ="Gjenerata")]
        public int GjenerataId { get; set; }
        [Display(Name = "Gjysemvjetori")]
        public int GjysmevjetoriId { get; set; }
        [Display(Name = "Shkolla")]
        public Nullable<int> ShkollaId { get; set; }
        [Range(0, int.MaxValue, ErrorMessage = "Nuk mund te vendosni numra negativ")]
        public Nullable<int> MungesaMeArsye { get; set; }
        [Range(0, int.MaxValue, ErrorMessage = "Nuk mund te vendosni numra negativ")]
        public Nullable<int> MungesaPaArsye { get; set; }
    
        public virtual Gjenerata Gjenerata { get; set; }
        public virtual Gjysmevjetori Gjysmevjetori { get; set; }
        public virtual Shkolla Shkolla { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormulariDetajet> FormulariDetajets { get; set; }

        public SelectList ListaGjenerata{ get; set; }
        public SelectList ListaGjysemvjetori { get; set; }
        public SelectList ListaShkolla { get; set; }

   
    }
}
