//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stats_V3
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;

    public partial class Gjenerata
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Gjenerata()
        {
            this.Formularis = new HashSet<Formulari>();
        }
    
        public int Id { get; set; }
        public int Paralelja { get; set; }
        public int Klasa { get; set; }
        public string FullInfo
        {
            get
            {
                return "Klasa "+Klasa + "/" + Paralelja;
            }
        }
        public Nullable<int> VitiShkolloreId { get; set; }
        public Nullable<int> ShkollaId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Formulari> Formularis { get; set; }
        public virtual Shkolla Shkolla { get; set; }
        public virtual VitiShkollore VitiShkollore { get; set; }
        public int NrFemra { get;  set; }
        public int NrMeshkuj { get;  set; }

        public SelectList ListaVitiShkollor { get; set; }
    }
}
