//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stats_V3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gjysmevjetori
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Gjysmevjetori()
        {
            this.Formularis = new HashSet<Formulari>();
        }
    
        public int Id { get; set; }
        public int Gjysmevjetori1 { get; set; }
        public Nullable<int> VitiShkolloreId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Formulari> Formularis { get; set; }
        public virtual VitiShkollore VitiShkollore { get; set; }
    }
}
