//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stats_V3
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class StatsV4Entities : DbContext
    {
        public StatsV4Entities()
            : base("name=StatsV4Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Formulari> Formularis { get; set; }
        public virtual DbSet<FormulariDetajet> FormulariDetajets { get; set; }
        public virtual DbSet<Gjenerata> Gjeneratas { get; set; }
        public virtual DbSet<Gjysmevjetori> Gjysmevjetoris { get; set; }
        public virtual DbSet<Lenda> Lendas { get; set; }
        public virtual DbSet<Shkolla> Shkollas { get; set; }
        public virtual DbSet<Suksesi> Suksesis { get; set; }
        public virtual DbSet<SuksesiLendor> SuksesiLendors { get; set; }
        public virtual DbSet<UserShkolla> UserShkollas { get; set; }
        public virtual DbSet<VitiShkollore> VitiShkollores { get; set; }
    
        public virtual int usp_Formulari_Insert(Nullable<int> prmGjenerataId, Nullable<int> prmGjysmevjetoriId, Nullable<int> prmMungesaPaArsye, Nullable<int> prmMungesaMeArsye)
        {
            var prmGjenerataIdParameter = prmGjenerataId.HasValue ?
                new ObjectParameter("prmGjenerataId", prmGjenerataId) :
                new ObjectParameter("prmGjenerataId", typeof(int));
    
            var prmGjysmevjetoriIdParameter = prmGjysmevjetoriId.HasValue ?
                new ObjectParameter("prmGjysmevjetoriId", prmGjysmevjetoriId) :
                new ObjectParameter("prmGjysmevjetoriId", typeof(int));
    
            var prmMungesaPaArsyeParameter = prmMungesaPaArsye.HasValue ?
                new ObjectParameter("prmMungesaPaArsye", prmMungesaPaArsye) :
                new ObjectParameter("prmMungesaPaArsye", typeof(int));
    
            var prmMungesaMeArsyeParameter = prmMungesaMeArsye.HasValue ?
                new ObjectParameter("prmMungesaMeArsye", prmMungesaMeArsye) :
                new ObjectParameter("prmMungesaMeArsye", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_Formulari_Insert", prmGjenerataIdParameter, prmGjysmevjetoriIdParameter, prmMungesaPaArsyeParameter, prmMungesaMeArsyeParameter);
        }
    }
}
