//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stats_V3
{
    using System;
    using System.Collections.Generic;
    
    public partial class SuksesiLendor
    {
        public int Id { get; set; }
        public int FormulariDetajetId { get; set; }
        public int LendaId { get; set; }
        public int SuksesiId { get; set; }
        public int NrNxenesveFemra { get; set; }
        public int NrNxenesveMeshkuj { get; set; }
    
        public virtual FormulariDetajet FormulariDetajet { get; set; }
        public virtual Lenda Lenda { get; set; }
        public virtual Suksesi Suksesi { get; set; }
    }
}
